//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_06_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int id { get; set; }
        public string EmployeeName { get; set; }
        public string Gender { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> DeptId { get; set; }
    }
}
